//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatersMusicPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkatersMusicPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All participants music has been connected.
        /// </summary>
        internal static string ALL_PARTICIPANTS_AUTOCONNECTED {
            get {
                return ResourceManager.GetString("ALL_PARTICIPANTS_AUTOCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoconnect.
        /// </summary>
        internal static string CAPTION_AUTOCONNECT {
            get {
                return ResourceManager.GetString("CAPTION_AUTOCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category?.
        /// </summary>
        internal static string CAPTION_DELETE_CATEGORY {
            get {
                return ResourceManager.GetString("CAPTION_DELETE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Participant?.
        /// </summary>
        internal static string CAPTION_DELETE_PARTICIPANT {
            get {
                return ResourceManager.GetString("CAPTION_DELETE_PARTICIPANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate use of music file.
        /// </summary>
        internal static string CAPTION_DUPLICATE_USE {
            get {
                return ResourceManager.GetString("CAPTION_DUPLICATE_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End program.
        /// </summary>
        internal static string CAPTION_END_PROGRAM {
            get {
                return ResourceManager.GetString("CAPTION_END_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string CAPTION_ERROR {
            get {
                return ResourceManager.GetString("CAPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading music!.
        /// </summary>
        internal static string CAPTION_ERROR_LOADING_MUSIC {
            get {
                return ResourceManager.GetString("CAPTION_ERROR_LOADING_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File imported.
        /// </summary>
        internal static string CAPTION_FILE_IMPORTED {
            get {
                return ResourceManager.GetString("CAPTION_FILE_IMPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music unzipped.
        /// </summary>
        internal static string CAPTION_FILES_UNZIPPED {
            get {
                return ResourceManager.GetString("CAPTION_FILES_UNZIPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        internal static string CAPTION_INVALID_FILE {
            get {
                return ResourceManager.GetString("CAPTION_INVALID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing music files.
        /// </summary>
        internal static string CAPTION_MISSING_MUSIC_FILES {
            get {
                return ResourceManager.GetString("CAPTION_MISSING_MUSIC_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event.
        /// </summary>
        internal static string CAPTION_NEW_COMPETITION {
            get {
                return ResourceManager.GetString("CAPTION_NEW_COMPETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file specified for participant.
        /// </summary>
        internal static string CAPTION_NO_FILE_FOR_PARTICIPANT {
            get {
                return ResourceManager.GetString("CAPTION_NO_FILE_FOR_PARTICIPANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing were unzipped.
        /// </summary>
        internal static string CAPTION_NO_FILES_UNZIPPED {
            get {
                return ResourceManager.GetString("CAPTION_NO_FILES_UNZIPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum error.
        /// </summary>
        internal static string CHECKSUM_ERROR {
            get {
                return ResourceManager.GetString("CHECKSUM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        internal static string INVALID_FILE {
            get {
                return ResourceManager.GetString("INVALID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file.
        /// </summary>
        internal static string NO_FILE {
            get {
                return ResourceManager.GetString("NO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No music files were unzipped! Verify zip-file or unzip manually.
        /// </summary>
        internal static string NO_MUSIC_FILES_UNZIPPED {
            get {
                return ResourceManager.GetString("NO_MUSIC_FILES_UNZIPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParticipantsMusic\.
        /// </summary>
        internal static string PARTICIPANT_MUSIC_DIRECTORY {
            get {
                return ResourceManager.GetString("PARTICIPANT_MUSIC_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback device error.
        /// </summary>
        internal static string PLAYBACK_DEVICE_ERROR {
            get {
                return ResourceManager.GetString("PLAYBACK_DEVICE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing break music....
        /// </summary>
        internal static string PLAYING_BREAK_MUSIC {
            get {
                return ResourceManager.GetString("PLAYING_BREAK_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing participants music....
        /// </summary>
        internal static string PLAYING_PARTICIPANT_MUSIC {
            get {
                return ResourceManager.GetString("PLAYING_PARTICIPANT_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing pause music....
        /// </summary>
        internal static string PLAYING_PAUSE_MUSIC {
            get {
                return ResourceManager.GetString("PLAYING_PAUSE_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing warmup music....
        /// </summary>
        internal static string PLAYING_WARMUP_MUSIC {
            get {
                return ResourceManager.GetString("PLAYING_WARMUP_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete entire event?.
        /// </summary>
        internal static string QUESTION_DELETE_COMPETITION {
            get {
                return ResourceManager.GetString("QUESTION_DELETE_COMPETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end the program?.
        /// </summary>
        internal static string QUESTION_END_PROGRAM {
            get {
                return ResourceManager.GetString("QUESTION_END_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories and Participants loaded from file. Edit Categories will now open to verify if category has Short.
        /// </summary>
        internal static string QUESTION_IMPORTED_VERIFY_SHORT {
            get {
                return ResourceManager.GetString("QUESTION_IMPORTED_VERIFY_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.xml.
        /// </summary>
        internal static string XML_FILENAME {
            get {
                return ResourceManager.GetString("XML_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string XMLTAG_CATEGORY {
            get {
                return ResourceManager.GetString("XMLTAG_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        internal static string XMLTAG_PARTICIPANT {
            get {
                return ResourceManager.GetString("XMLTAG_PARTICIPANT", resourceCulture);
            }
        }
    }
}
